<?php
session_start();
require_once "../config/db.php";
require_once __DIR__ . '/../vendor/autoload.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$user_id = $_SESSION['user_id'] ?? null;

$name = $_POST['name'] ?? null;
$phone = $_POST['phone'] ?? null;
$landmark = $_POST['landmark'] ?? null;
$location = $_POST['location'] ?? null;
$type = $_POST['type'] ?? null;

if(!$name || !$phone || !$landmark || !$location || !$type){
    die("Missing required fields");
}

$stmt = $conn->prepare("
INSERT INTO emergency_requests
(user_id, name, phone, landmark, location, latitude, longitude, emergency_type)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
");

$stmt->bind_param(
    "isssssss",
    $user_id,
    $name,
    $phone,
    $landmark,
    $location,
    $latitude,
    $longitude,
    $type
);

$stmt->execute();


$mail = new PHPMailer(true);

try {
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'sendersmail';
    $mail->Password = ''; 
    $mail->SMTPSecure = 'tls';
    $mail->Port = 587;

$time = date("Y-m-d H:i:s");


    $mail->setFrom('sendersmail', 'Fixigo Emergency');
    $mail->addAddress('resiversmail');

   $mail->Subject = 'Emergency Request ';
   $mail->Body    = "Dear Fixigo Team,\n\n".
                 "An emergency situation.\n\n".
                 "Details:\n".
                 "Name: $name\n".
                 "Time of request: $time\n".
                 "Phone: $phone\n".
                 "Landmark: $landmark\n".
                 "Location: $location\n".
                 "Maps: https://maps.google.com/?q=$location\n\n".
                 "⚠️ Please treat this as urgent and respond immediately.\n\n".
                 "This message was automatically generated by the Fixigo Emergency Service.";
   $mail->addAttachment('../images/police.png', 'police.png');

    $mail->send();
    echo "EMAIL SENT SUCCESSFULLY";
} catch (Exception $e) {
    echo "EMAIL ERROR: {$mail->ErrorInfo}";
}
?>
